//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1___Database_first
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrderHead()
        {
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime Orderdate { get; set; }
        public string DeliveryAdress { get; set; }
        public int CityID { get; set; }
        public int ZipcodeID { get; set; }
        public int CustomerID { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblZipcode tblZipcode { get; set; }
    }
}
