//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1___Database_first
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblOrderHeads = new HashSet<tblOrderHead>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string StreetAdress { get; set; }
        public int ZipcodeID { get; set; }
        public int CityID { get; set; }
        public int CustomergroupID { get; set; }
        public bool Admin { get; set; }
        public string email { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCustomerGroup tblCustomerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderHead> tblOrderHeads { get; set; }
        public virtual tblZipcode tblZipcode { get; set; }
    }
}
